import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import DownloadButton from "../components/downloadButton";
import Header from "@/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-y-scroll scroll-smooth" >
      <body className= "" suppressHydrationWarning={true}>
        <StoreProvider>
          <Header />
          <section className=" h-screen">{children}</section>
        </StoreProvider>
      </body>
    </html>
  );
}
